using System;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Windows.Forms;

namespace DumpImageToCode
{
    /// <summary>
    /// Dumps an image to a text file which can be used as inline code.
    /// </summary>
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            openFileDialog1.Title = "Select Image file";
            openFileDialog1.Multiselect = false;
            openFileDialog1.Filter = "Image files (*.jpg,*.png)|*.jpg;*.png";
            openFileDialog1.FilterIndex = 0;
            openFileDialog1.FileName = string.Empty;
            openFileDialog1.InitialDirectory = Application.StartupPath;         // Open in current directory

            if (openFileDialog1.ShowDialog() == DialogResult.OK)
            {
                this.textBox1.Text = openFileDialog1.FileName;
            }
        }

        /// <summary>
        /// Convert Image to byte array and save as hex code in text file.
        /// Test by loading the file and displaying the image.
        /// </summary>
        /// <param name="imageFilename">The image file name</param>
        private void DumpToCode(string imageFilename)
        {
            byte[] arr;
            Image image = Image.FromFile(imageFilename);
            Image testImage;
            string dumpFilename = string.Empty;

            using (MemoryStream ms = new MemoryStream())
            {
                Bitmap bmp = new Bitmap(image);

                if (imageFilename.EndsWith(".png"))
                {
                    bmp.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                    dumpFilename = imageFilename.Replace(".png", ".txt");
                }
                if (imageFilename.EndsWith(".jpg"))
                {
                    bmp.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg);
                    dumpFilename = imageFilename.Replace(".jpg", ".txt");
                }

                arr = ms.ToArray();
            }

            if (!string.IsNullOrEmpty(dumpFilename))
            {
                string hex = string.Join(" ", arr.Select(x => x.ToString("X2")));

                //Debug.Print(hex);
                File.WriteAllText(dumpFilename, hex);

                // Test: load image from hex file and display in picturebox
                testImage = LoadImageFromDump(dumpFilename);
                this.pictureBox1.Image = testImage;
            }
        }

        private Image LoadImageFromDump(string fileName)
        {
            string hex2 = File.ReadAllText(fileName);
            var hexArr = hex2.Split(' ');
            byte[] arr2 = new byte[hexArr.Length];

            for (int i = 0; i < hexArr.Length; i++)
            {
                arr2[i] = Convert.ToByte(hexArr[i], 16);
            }

            using (var ms2 = new MemoryStream(arr2))
            {
                return Image.FromStream(ms2);
            }
        }

        /// <summary>
        /// Get an image from a string generated by the DumpImageToCode tool.
        /// </summary>
        /// <param name="hexString">The string with hex codes</param>
        /// <returns>An image</returns>
        private Image GetImageFromHexString(string hexString)
        {
            //string plus = "89 50 4E 47 0D 0A 1A 0A 00 00 00 0D 49 48 44 52 00 00 00 1A 00 00 00 1A 08 06 00 00 00 A9 4A 4C CE 00 00 00 01 73 52 47 42 00 AE CE 1C E9 00 00 00 04 67 41 4D 41 00 00 B1 8F 0B FC 61 05 00 00 00 09 70 48 59 73 00 00 0E C3 00 00 0E C3 01 C7 6F A8 64 00 00 00 58 49 44 41 54 48 4B ED 93 51 0A 00 21 08 44 BD FF C5 6A F7 52 E5 C2 06 11 1A 31 62 5F F3 E0 FD 88 3A 5F 23 E4 16 AF DA 7E EB 37 C8 62 84 0C D3 60 10 0C 83 5C E6 9E 44 DD F6 CC 3A 88 E8 62 2D 47 74 79 54 EB 00 B1 A8 30 EB B3 34 18 04 C3 20 98 B9 67 A1 9E 90 43 44 3A 27 6F 8D BD 18 59 7F D5 00 00 00 00 49 45 4E 44 AE 42 60 82";
            var hexArr = hexString.Split(' ');
            byte[] arr2 = new byte[hexArr.Length];

            for (int i = 0; i < hexArr.Length; i++)
            {
                arr2[i] = Convert.ToByte(hexArr[i], 16);
            }

            using (var ms2 = new MemoryStream(arr2))
            {
                return Image.FromStream(ms2);
            }
        }

        private void buttonOk_Click(object sender, EventArgs e)
        {
            DumpToCode(this.textBox1.Text);
        }
    }
}